apiVersion: v1
kind: Service
metadata:
  name: phase2-service
spec:
  type: NodePort
  selector:
    app: probe-demo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30012  # Or remove for auto-assigned
